# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7fbe0566b4423cfbbed53bcad8f7aea2d24cca7ff82b0aa153b74867ea0da7cbcd1b7ef5cf4edc6c426d9222b3fd6209e54edc479f57708a1192b819b94103

test:
  secret_key_base: b875beac0a3ffe3f93bcccf4f074baf0adbd1e376753e3af3bd510a5c2ce03a237b13639bc586c94de7ee3dd7d20b36ba925302678c1e631530bee1259340cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
